### ISSUE TITLE
Deleting VP causes warning and directory permissions change on site directory

### ISSUE THREAD

**Issue by unclhos** [versionpress/versionpress#945]
VP 3.0-Beta
PHP 5.6.19

> Warning: include(/home/brianli/public_html/2016.dev/vptemplate/wp-content/plugins/versionpress/src/Database/WpdbMirrorBridge.php): failed to open stream: No such file or directory in /home/brianli/public_html/2016.dev/vptemplate/wp-content/plugins/versionpress/vendor/composer/ClassLoader.php on line 412

> Warning: include(): Failed opening '/home/brianli/public_html/2016.dev/vptemplate/wp-content/plugins/versionpress/src/Database/WpdbMirrorBridge.php' for inclusion (include_path='.:/usr/lib/php:/usr/local/lib/php') in /home/brianli/public_html/2016.dev/vptemplate/wp-content/plugins/versionpress/vendor/composer/ClassLoader.php on line 412

> Fatal error: Class 'VersionPress\Database\WpdbMirrorBridge' not found in /home/brianli/public_html/2016.dev/vptemplate/wp-content/plugins/versionpress/src/DI/DIContainer.php on line 85

Site directory permissions changed to 750 after plugin deletion, causing site to be inaccessible.

**Comment by borekb** [comment]
Possibly related: https://github.com/versionpress/versionpress/pull/937

**Comment by JanVoracek** [comment]
The first bug (warnings and fatal error) is already fixed in #937. 

"Site directory permissions changed to 750" – that's weird. VersionPress changes permission only for the `.git` directory. Also, the web should work with 750. I think the site was broken because of the first error.

**Comment by unclhos** [comment]
The site goes to 403 forbidden in 750., once i change permissions back it back it works. But ill look into my server configuration. Any reason why the permissions are changed just because of deleting the plugin though? This is after deactivation.

**Comment by unclhos** [comment]
Ah you said it was changing the .git, at this point the .git is gone and its the site directory that was changed.

**Comment by JanVoracek** [comment]
Unfortunately, I cannot reproduce it. I have 755 before and after deleting. VersionPress sets permissions only of the `.git` directory, new directories and our custom merge driver. It doesn't change permissions of the whole site (or I don't know how it could happen).

**Comment by unclhos** [comment]
Ok I figured out the forbidden problem. I'm running in a subdirectory and the group was set to the cpanel user instead of "nobody" so when it changes to 750 it has issues. But I still see it changing it to 750 upon deletion. FYI 2.2 was changing it to 777 (Both times starting at 755)

**Comment by JanVoracek** [comment]
@octopuss: Can you try to reproduce this?

**Comment by octopuss** [comment]
@JanVoracek : I've tried to reproduce it but no success. I tried 2 ways to install VersionPress (listed below), and then perform uninstall and delete.

- building version from current master and installing it manually
- using WpAutomation class and installing it automatically

**Comment by unclhos** [comment]
I think I have narrowed it down a bit more. it doesn't do it when i'm at the server web root. but it does do it when the site is in a sub directory of web root. i have a test site on my server if you want to play with it. Just email to get some creds.

**Comment by borekb** [comment]
@unclhos We unfortunately still have no idea what might be causing this. Could you try to reproduce on a different machine just to be sure it is reproducible?

**Comment by unclhos** [comment]
I was going to do it locally but the php 5.6 requirement keeps me from attempting. Has someone else attempted it in a sub directory? I'll hack the requirements when I can to attempt it locally.

**Comment by borekb** [comment]
I'm moving this to 3.0.1 so that it doesn't block the 3.0 release.

**Comment by pavelevap** [comment]
I was able to reproduce this behaviour with my general Dreamhost account. I deleted one plugin and everything was fine. Then I deleted VP and received "403 Forbidden", because of CHMOD change of the whole `mydomain` directory from 755 to 750. But `versionpress` folder, `vpdb` and `.git` repo was deleted successfully. BTW, `vpbackups` folder should be deleted too during uninstallation?

In `error.log` I have only following (but I will have to check actual `error_reporting`):

`(13)Permission denied: /home/pavelevap/mydomain/.htaccess pcfg_openfile: unable to check htaccess file`

**Comment by borekb** [comment]
There are three occurrences of `750` in our code:

1. [MergeDriverInstaller](https://github.com/versionpress/versionpress/blob/bd898332523ec68097315f3de7cf2e385537d208/plugins/versionpress/src/Git/MergeDriverInstaller.php#L97-L97)
2. [FileSystem::mkdir()](https://github.com/versionpress/versionpress/blob/bd898332523ec68097315f3de7cf2e385537d208/plugins/versionpress/src/Utils/FileSystem.php#L117-L117)
3. [FileSystem::possiblyFixGitPermissions()](https://github.com/versionpress/versionpress/blob/bd898332523ec68097315f3de7cf2e385537d208/plugins/versionpress/src/Utils/FileSystem.php#L149-L149)

In neither case are the permissions set on the root directory so it's still a mystery what's going on. @pavelevap, could you try updating those three places to some slightly different permissions, like 751, 757 or something similar to find out which occurrence is causing it?

**Comment by pavelevap** [comment]
@borekb: Yes, I am testing it now and I am getting really close :-) I am sure that problem is exactly with `possiblyFixGitPermissions()` function.

My passed `$gitDir` is `/home/pavelevap/mydomain//.git`.
And when I see `$iterator` and loop through all `$items`, first of them are:

```
/home/pavelevap/mydomain//.git/.
/home/pavelevap/mydomain//.git/..
/home/pavelevap/mydomain//.git/refs/.
....
```

And `/home/pavelevap/mydomain//.git/..` leads with double dot to parent directory `/home/pavelevap/mydomain` and makes this directory restricted to `750`, I guess. We should probably use `SELF_FIRST` or `SKIP_DOTS` here for `RecursiveIteratorIterator`? But I am not sure, it is too late to study docs now :-)

**Comment by borekb** [comment]
Nice find! Another option would be to get rid of this function entirely – it was added a long time ago, supposedly because of Windows, and I'm not sure we still need it. Let's wait for @JanVoracek's opinion on this.

**Comment by JanVoracek** [comment]
@octopuss: Let's start with removing the `VersionPress\Utils\FileSystem::possiblyFixGitPermissions` method and let @borekb to try it on Windows.

**Comment by octopuss** [comment]
@borekb: could you try it on 981e0e2 please ?

**Comment by borekb** [comment]
Removing `VersionPress\Utils\FileSystem::possiblyFixGitPermissions()` in PR #1051 unfortunately causes some issues on Windows, I need to look into it further.

**Comment by borekb** [comment]
Finally resolved by PR https://github.com/versionpress/versionpress/pull/1062.
